### ISSUE TITLE
Allow passing extra metadata from the command line

### ISSUE THREAD

**Issue by marcaddeo** [marcaddeo/docdoc#5]
Implement a `--extra-metadata` flag to pass metadata in through the command line.

This should work a lot like Ansible's `--extra-vars` flag, and similarly will take precedence over all metadata.

### YAML
`docdoc --extra-metadata="title: Something" -e "subtitle: something" docs/example.md docs/dist`

### YAML file
**`docs/navigation.yml`**
```yaml
navigation:
  - name: Home
    path: /index.html
  - name: About
    path: /about.html
```
`docdoc --extra-metadata="@docs/navigation.yml" docs/about.html docs/dist`
