### ISSUE TITLE
Allow theme metadata to include other files

### ISSUE THREAD

**Issue by marcaddeo** [marcaddeo/docdoc#6]
Would likely be nice to be able to do something like:

```yaml
name: example_theme

metadata:
  - title: Default title
  - include: @navigation.yml

assets:
  - assets
```
